<?php

/**
 * @file
 * Contains group_welcome_message.module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\Access\AccessInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\group\Entity\Group;
use Drupal\group\Entity\GroupInterface;

/**
 * Implements hook_help().
 */
function group_welcome_message_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_welcome_message module.
    case 'help.page.group_welcome_message':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds welcome messages for Group') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_group_buttons_add_button_alter()
 */
function group_welcome_message_group_buttons_add_button_alter(&$buttons) {

  // Get current group so we can build correct links.
  $group = \Drupal::routeMatch()->getParameter('group');

  if (!is_object($group) && !is_null($group)) {

    $group = \Drupal::entityTypeManager()
      ->getStorage('group')
      ->load($group);

  }

  if ($group instanceof GroupInterface) {

    $buttons['manage_welcome_message'] = [
      '#type' => 'link',
      '#title' => t('Manage Welcome Message'),
      '#url' => Url::fromRoute('entity.group_welcome_message.add_form', ['group' => $group->id()]
          ),
      '#attributes' => [
        'class' => ['group-welcome-message-action-button','button', 'btn','btn-default'],
      ],
    ];

  }

}

